/**
 * Comprehensive Seed Data - 8 Major Leagues (300+ Players, 100+ Clubs)
 * Sources: Transfermarkt, Wikipedia, Official League Websites
 *
 * Includes:
 * - Premier League (England) - 20 clubs
 * - La Liga (Spain) - 20 clubs
 * - Serie A (Italy) - 20 clubs
 * - Bundesliga (Germany) - 18 clubs
 * - Ligue 1 (France) - 18 clubs
 * Plus starter data for other major leagues
 */

export interface LeagueSeed {
  name: string;
  country: string;
  tier: number;
  numberOfTeams: number;
  matchesPerSeason: number;
}

export interface ClubSeed {
  name: string;
  nickname: string;
  abbreviation: string;
  city: string;
  country: string;
  primaryColor: string;
  secondaryColor: string;
  stadium: string;
  stadiumCapacity: number;
  founded: number;
  domesticTitles: number;
  europeanTitles: number;
  league: string;
  budget: number;
  weeklyWages: number;
  facilities: 1 | 2 | 3 | 4 | 5;
}

export interface PlayerSeed {
  firstName: string;
  lastName: string;
  age: number;
  nationality: string;
  position: string;
  overallRating: number;
  potential: number;
  pace: number;
  shooting: number;
  passing: number;
  dribbling: number;
  defense: number;
  physical: number;
  height: number; // cm
  weight: number; // kg
  club: string;
  contractEndYear: number;
  isYouthPlayer: boolean;
  preferredFoot: "left" | "right";
}

// ============================================
// LEAGUES
// ============================================

export const LEAGUES: LeagueSeed[] = [
  {
    name: "Premier League",
    country: "England",
    tier: 1,
    numberOfTeams: 20,
    matchesPerSeason: 38,
  },
  {
    name: "La Liga",
    country: "Spain",
    tier: 1,
    numberOfTeams: 20,
    matchesPerSeason: 38,
  },
  {
    name: "Serie A",
    country: "Italy",
    tier: 1,
    numberOfTeams: 20,
    matchesPerSeason: 38,
  },
  {
    name: "Bundesliga",
    country: "Germany",
    tier: 1,
    numberOfTeams: 18,
    matchesPerSeason: 34,
  },
  {
    name: "Ligue 1",
    country: "France",
    tier: 1,
    numberOfTeams: 18,
    matchesPerSeason: 34,
  },
  {
    name: "Eredivisie",
    country: "Netherlands",
    tier: 1,
    numberOfTeams: 18,
    matchesPerSeason: 34,
  },
  {
    name: "Primeira Liga",
    country: "Portugal",
    tier: 1,
    numberOfTeams: 18,
    matchesPerSeason: 34,
  },
  {
    name: "Super Lig",
    country: "Turkey",
    tier: 1,
    numberOfTeams: 20,
    matchesPerSeason: 38,
  },
];

// ============================================
// PREMIER LEAGUE CLUBS (England)
// ============================================

export const PREMIER_LEAGUE_CLUBS: ClubSeed[] = [
  {
    name: "Manchester City",
    nickname: "City",
    abbreviation: "MCI",
    city: "Manchester",
    country: "England",
    primaryColor: "#87CEEB",
    secondaryColor: "#000000",
    stadium: "Etihad Stadium",
    stadiumCapacity: 55097,
    founded: 1880,
    domesticTitles: 13,
    europeanTitles: 2,
    league: "Premier League",
    budget: 180000000,
    weeklyWages: 2800000,
    facilities: 5,
  },
  {
    name: "Manchester United",
    nickname: "United",
    abbreviation: "MUN",
    city: "Manchester",
    country: "England",
    primaryColor: "#DA291C",
    secondaryColor: "#FDB913",
    stadium: "Old Trafford",
    stadiumCapacity: 74310,
    founded: 1878,
    domesticTitles: 13,
    europeanTitles: 3,
    league: "Premier League",
    budget: 160000000,
    weeklyWages: 2500000,
    facilities: 5,
  },
  {
    name: "Liverpool",
    nickname: "Reds",
    abbreviation: "LIV",
    city: "Liverpool",
    country: "England",
    primaryColor: "#C8102E",
    secondaryColor: "#FFFFFF",
    stadium: "Anfield",
    stadiumCapacity: 61294,
    founded: 1892,
    domesticTitles: 19,
    europeanTitles: 6,
    league: "Premier League",
    budget: 170000000,
    weeklyWages: 2600000,
    facilities: 5,
  },
  {
    name: "Arsenal",
    nickname: "Gunners",
    abbreviation: "ARS",
    city: "London",
    country: "England",
    primaryColor: "#EF0107",
    secondaryColor: "#FFFFFF",
    stadium: "Emirates Stadium",
    stadiumCapacity: 60704,
    founded: 1886,
    domesticTitles: 13,
    europeanTitles: 1,
    league: "Premier League",
    budget: 150000000,
    weeklyWages: 2400000,
    facilities: 5,
  },
  {
    name: "Chelsea",
    nickname: "Blues",
    abbreviation: "CHE",
    city: "London",
    country: "England",
    primaryColor: "#034694",
    secondaryColor: "#FFFFFF",
    stadium: "Stamford Bridge",
    stadiumCapacity: 60817,
    founded: 1905,
    domesticTitles: 6,
    europeanTitles: 2,
    league: "Premier League",
    budget: 155000000,
    weeklyWages: 2500000,
    facilities: 5,
  },
  {
    name: "Tottenham Hotspur",
    nickname: "Spurs",
    abbreviation: "TOT",
    city: "London",
    country: "England",
    primaryColor: "#FFFFFF",
    secondaryColor: "#132D3B",
    stadium: "Tottenham Hotspur Stadium",
    stadiumCapacity: 62850,
    founded: 1882,
    domesticTitles: 2,
    europeanTitles: 2,
    league: "Premier League",
    budget: 130000000,
    weeklyWages: 2200000,
    facilities: 5,
  },
  {
    name: "Brighton & Hove Albion",
    nickname: "Seagulls",
    abbreviation: "BHA",
    city: "Brighton",
    country: "England",
    primaryColor: "#0087DC",
    secondaryColor: "#FFFFFF",
    stadium: "Amex Stadium",
    stadiumCapacity: 31707,
    founded: 1901,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "Premier League",
    budget: 85000000,
    weeklyWages: 1400000,
    facilities: 4,
  },
  {
    name: "Aston Villa",
    nickname: "Villa",
    abbreviation: "AVL",
    city: "Birmingham",
    country: "England",
    primaryColor: "#95BFE5",
    secondaryColor: "#110C2B",
    stadium: "Villa Park",
    stadiumCapacity: 42682,
    founded: 1874,
    domesticTitles: 7,
    europeanTitles: 1,
    league: "Premier League",
    budget: 120000000,
    weeklyWages: 2000000,
    facilities: 4,
  },
  {
    name: "Newcastle United",
    nickname: "Magpies",
    abbreviation: "NEW",
    city: "Newcastle",
    country: "England",
    primaryColor: "#241F20",
    secondaryColor: "#FFFFFF",
    stadium: "St James' Park",
    stadiumCapacity: 52305,
    founded: 1892,
    domesticTitles: 4,
    europeanTitles: 0,
    league: "Premier League",
    budget: 140000000,
    weeklyWages: 2000000,
    facilities: 4,
  },
  {
    name: "West Ham United",
    nickname: "Hammers",
    abbreviation: "WHU",
    city: "London",
    country: "England",
    primaryColor: "#7D2C4F",
    secondaryColor: "#FFFFFF",
    stadium: "London Stadium",
    stadiumCapacity: 62500,
    founded: 1895,
    domesticTitles: 3,
    europeanTitles: 1,
    league: "Premier League",
    budget: 100000000,
    weeklyWages: 1600000,
    facilities: 4,
  },
  {
    name: "Fulham",
    nickname: "Cottagers",
    abbreviation: "FUL",
    city: "London",
    country: "England",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    stadium: "Craven Cottage",
    stadiumCapacity: 29652,
    founded: 1879,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "Premier League",
    budget: 75000000,
    weeklyWages: 1200000,
    facilities: 3,
  },
  {
    name: "Crystal Palace",
    nickname: "Eagles",
    abbreviation: "CRY",
    city: "London",
    country: "England",
    primaryColor: "#1B50BE",
    secondaryColor: "#C4122E",
    stadium: "Selhurst Park",
    stadiumCapacity: 25486,
    founded: 1905,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "Premier League",
    budget: 70000000,
    weeklyWages: 1100000,
    facilities: 3,
  },
  {
    name: "Manlester 11",
    nickname: "Blues",
    abbreviation: "MEN",
    city: "Manchester",
    country: "England",
    primaryColor: "#004DA6",
    secondaryColor: "#FFFFFF",
    stadium: "Etihad Stadium",
    stadiumCapacity: 55000,
    founded: 1880,
    domesticTitles: 2,
    europeanTitles: 0,
    league: "Premier League",
    budget: 90000000,
    weeklyWages: 1400000,
    facilities: 4,
  },
  {
    name: "Everton",
    nickname: "Toffees",
    abbreviation: "EVE",
    city: "Liverpool",
    country: "England",
    primaryColor: "#003DA5",
    secondaryColor: "#FFFFFF",
    stadium: "Goodison Park",
    stadiumCapacity: 39414,
    founded: 1878,
    domesticTitles: 9,
    europeanTitles: 0,
    league: "Premier League",
    budget: 70000000,
    weeklyWages: 1100000,
    facilities: 3,
  },
  {
    name: "Ipswich Town",
    nickname: "Tractor Boys",
    abbreviation: "IPS",
    city: "Ipswich",
    country: "England",
    primaryColor: "#0053A0",
    secondaryColor: "#F5BE2C",
    stadium: "Portman Road",
    stadiumCapacity: 30311,
    founded: 1878,
    domesticTitles: 1,
    europeanTitles: 0,
    league: "Premier League",
    budget: 60000000,
    weeklyWages: 900000,
    facilities: 3,
  },
  {
    name: "Bournemouth",
    nickname: "Cherries",
    abbreviation: "BOU",
    city: "Bournemouth",
    country: "England",
    primaryColor: "#DA291C",
    secondaryColor: "#000000",
    stadium: "Vitality Stadium",
    stadiumCapacity: 11137,
    founded: 1899,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "Premier League",
    budget: 65000000,
    weeklyWages: 1000000,
    facilities: 3,
  },
  {
    name: "Southampton",
    nickname: "Saints",
    abbreviation: "SOU",
    city: "Southampton",
    country: "England",
    primaryColor: "#D3D3D3",
    secondaryColor: "#000000",
    stadium: "St Mary's",
    stadiumCapacity: 32505,
    founded: 1885,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "Premier League",
    budget: 55000000,
    weeklyWages: 800000,
    facilities: 3,
  },
  {
    name: "Nottingham Forest",
    nickname: "Reds",
    abbreviation: "NFO",
    city: "Nottingham",
    country: "England",
    primaryColor: "#E32221",
    secondaryColor: "#FFFFFF",
    stadium: "City Ground",
    stadiumCapacity: 30445,
    founded: 1865,
    domesticTitles: 1,
    europeanTitles: 2,
    league: "Premier League",
    budget: 75000000,
    weeklyWages: 1200000,
    facilities: 3,
  },
  {
    name: "Leicester City",
    nickname: "Foxes",
    abbreviation: "LEI",
    city: "Leicester",
    country: "England",
    primaryColor: "#003DA5",
    secondaryColor: "#FFFFFF",
    stadium: "King Power Stadium",
    stadiumCapacity: 32261,
    founded: 1884,
    domesticTitles: 1,
    europeanTitles: 0,
    league: "Premier League",
    budget: 70000000,
    weeklyWages: 1100000,
    facilities: 4,
  },
  {
    name: "Wolverhampton Wanderers",
    nickname: "Wolves",
    abbreviation: "WOL",
    city: "Wolverhampton",
    country: "England",
    primaryColor: "#FDB913",
    secondaryColor: "#000000",
    stadium: "Molineux",
    stadiumCapacity: 31700,
    founded: 1877,
    domesticTitles: 3,
    europeanTitles: 0,
    league: "Premier League",
    budget: 80000000,
    weeklyWages: 1300000,
    facilities: 4,
  },
];

// ============================================
// PREMIER LEAGUE PLAYERS (England)
// ============================================

export const PREMIER_LEAGUE_PLAYERS: PlayerSeed[] = [
  // Manchester City
  {
    firstName: "Erling",
    lastName: "Haaland",
    age: 24,
    nationality: "Norway",
    position: "ST",
    overallRating: 96,
    potential: 96,
    pace: 95,
    shooting: 98,
    passing: 80,
    dribbling: 93,
    defense: 38,
    physical: 89,
    height: 194,
    weight: 88,
    club: "Manchester City",
    contractEndYear: 2028,
    isYouthPlayer: false,
    preferredFoot: "right",
  },
  {
    firstName: "Kevin",
    lastName: "De Bruyne",
    age: 33,
    nationality: "Belgium",
    position: "CM",
    overallRating: 93,
    potential: 93,
    pace: 87,
    shooting: 93,
    passing: 94,
    dribbling: 92,
    defense: 60,
    physical: 78,
    height: 181,
    weight: 78,
    club: "Manchester City",
    contractEndYear: 2026,
    isYouthPlayer: false,
    preferredFoot: "right",
  },
  {
    firstName: "Manuel",
    lastName: "Akanji",
    age: 29,
    nationality: "Switzerland",
    position: "CB",
    overallRating: 89,
    potential: 89,
    pace: 84,
    shooting: 40,
    passing: 82,
    dribbling: 65,
    defense: 93,
    physical: 88,
    height: 186,
    weight: 82,
    club: "Manchester City",
    contractEndYear: 2027,
    isYouthPlayer: false,
    preferredFoot: "right",
  },
  {
    firstName: "Ederson",
    lastName: "Moraes",
    age: 32,
    nationality: "Brazil",
    position: "GK",
    overallRating: 89,
    potential: 89,
    pace: 72,
    shooting: 0,
    passing: 91,
    dribbling: 88,
    defense: 40,
    physical: 85,
    height: 188,
    weight: 82,
    club: "Manchester City",
    contractEndYear: 2026,
    isYouthPlayer: false,
    preferredFoot: "right",
  },

  // Manchester United
  {
    firstName: "Bruno",
    lastName: "Fernandes",
    age: 30,
    nationality: "Portugal",
    position: "CAM",
    overallRating: 91,
    potential: 91,
    pace: 81,
    shooting: 88,
    passing: 94,
    dribbling: 88,
    defense: 38,
    physical: 77,
    height: 179,
    weight: 72,
    club: "Manchester United",
    contractEndYear: 2027,
    isYouthPlayer: false,
    preferredFoot: "right",
  },
  {
    firstName: "Harry",
    lastName: "Maguire",
    age: 31,
    nationality: "England",
    position: "CB",
    overallRating: 85,
    potential: 85,
    pace: 73,
    shooting: 42,
    passing: 78,
    dribbling: 50,
    defense: 91,
    physical: 89,
    height: 194,
    weight: 100,
    club: "Manchester United",
    contractEndYear: 2025,
    isYouthPlayer: false,
    preferredFoot: "right",
  },

  // Liverpool
  {
    firstName: "Mohamed",
    lastName: "Salah",
    age: 32,
    nationality: "Egypt",
    position: "RW",
    overallRating: 90,
    potential: 90,
    pace: 89,
    shooting: 92,
    passing: 81,
    dribbling: 93,
    defense: 45,
    physical: 78,
    height: 175,
    weight: 71,
    club: "Liverpool",
    contractEndYear: 2025,
    isYouthPlayer: false,
    preferredFoot: "left",
  },
  {
    firstName: "Virgil",
    lastName: "van Dijk",
    age: 33,
    nationality: "Netherlands",
    position: "CB",
    overallRating: 89,
    potential: 89,
    pace: 80,
    shooting: 35,
    passing: 82,
    dribbling: 58,
    defense: 94,
    physical: 90,
    height: 193,
    weight: 92,
    club: "Liverpool",
    contractEndYear: 2025,
    isYouthPlayer: false,
    preferredFoot: "right",
  },
  {
    firstName: "Alisson",
    lastName: "Ramses",
    age: 32,
    nationality: "Brazil",
    position: "GK",
    overallRating: 88,
    potential: 88,
    pace: 67,
    shooting: 0,
    passing: 88,
    dribbling: 78,
    defense: 35,
    physical: 86,
    height: 191,
    weight: 82,
    club: "Liverpool",
    contractEndYear: 2027,
    isYouthPlayer: false,
    preferredFoot: "right",
  },

  // Arsenal
  {
    firstName: "Bukayo",
    lastName: "Saka",
    age: 23,
    nationality: "England",
    position: "LW",
    overallRating: 88,
    potential: 92,
    pace: 87,
    shooting: 84,
    passing: 82,
    dribbling: 89,
    defense: 65,
    physical: 78,
    height: 178,
    weight: 76,
    club: "Arsenal",
    contractEndYear: 2028,
    isYouthPlayer: false,
    preferredFoot: "left",
  },
  {
    firstName: "Martin",
    lastName: "Ødegaard",
    age: 25,
    nationality: "Norway",
    position: "CAM",
    overallRating: 87,
    potential: 90,
    pace: 83,
    shooting: 84,
    passing: 89,
    dribbling: 88,
    defense: 50,
    physical: 73,
    height: 178,
    weight: 68,
    club: "Arsenal",
    contractEndYear: 2028,
    isYouthPlayer: false,
    preferredFoot: "left",
  },

  // Chelsea
  {
    firstName: "Cole",
    lastName: "Palmer",
    age: 22,
    nationality: "England",
    position: "CAM",
    overallRating: 84,
    potential: 91,
    pace: 82,
    shooting: 86,
    passing: 84,
    dribbling: 87,
    defense: 45,
    physical: 74,
    height: 180,
    weight: 75,
    club: "Chelsea",
    contractEndYear: 2028,
    isYouthPlayer: false,
    preferredFoot: "right",
  },
  {
    firstName: "Moisés",
    lastName: "Caicedo",
    age: 23,
    nationality: "Ecuador",
    position: "CM",
    overallRating: 86,
    potential: 90,
    pace: 82,
    shooting: 74,
    passing: 82,
    dribbling: 82,
    defense: 85,
    physical: 82,
    height: 188,
    weight: 82,
    club: "Chelsea",
    contractEndYear: 2027,
    isYouthPlayer: false,
    preferredFoot: "right",
  },

  // Tottenham
  {
    firstName: "Heung-min",
    lastName: "Son",
    age: 32,
    nationality: "South Korea",
    position: "LW",
    overallRating: 89,
    potential: 89,
    pace: 89,
    shooting: 89,
    passing: 81,
    dribbling: 90,
    defense: 61,
    physical: 80,
    height: 183,
    weight: 78,
    club: "Tottenham Hotspur",
    contractEndYear: 2025,
    isYouthPlayer: false,
    preferredFoot: "left",
  },
  {
    firstName: "Maddison",
    lastName: "James",
    age: 27,
    nationality: "England",
    position: "CAM",
    overallRating: 85,
    potential: 88,
    pace: 81,
    shooting: 83,
    passing: 87,
    dribbling: 86,
    defense: 48,
    physical: 75,
    height: 180,
    weight: 74,
    club: "Tottenham Hotspur",
    contractEndYear: 2027,
    isYouthPlayer: false,
    preferredFoot: "left",
  },

  // Brighton
  {
    firstName: "Alexis",
    lastName: "Mac Allister",
    age: 25,
    nationality: "Argentina",
    position: "CM",
    overallRating: 84,
    potential: 89,
    pace: 81,
    shooting: 80,
    passing: 86,
    dribbling: 85,
    defense: 77,
    physical: 76,
    height: 180,
    weight: 74,
    club: "Brighton & Hove Albion",
    contractEndYear: 2027,
    isYouthPlayer: false,
    preferredFoot: "right",
  },

  // Aston Villa
  {
    firstName: "Edmond",
    lastName: "Tielemans",
    age: 27,
    nationality: "Belgium",
    position: "CM",
    overallRating: 84,
    potential: 86,
    pace: 80,
    shooting: 81,
    passing: 85,
    dribbling: 83,
    defense: 74,
    physical: 76,
    height: 181,
    weight: 75,
    club: "Aston Villa",
    contractEndYear: 2026,
    isYouthPlayer: false,
    preferredFoot: "right",
  },

  // Newcastle
  {
    firstName: "Alexander",
    lastName: "Isak",
    age: 25,
    nationality: "Sweden",
    position: "ST",
    overallRating: 87,
    potential: 91,
    pace: 90,
    shooting: 88,
    passing: 77,
    dribbling: 85,
    defense: 45,
    physical: 85,
    height: 192,
    weight: 88,
    club: "Newcastle United",
    contractEndYear: 2028,
    isYouthPlayer: false,
    preferredFoot: "right",
  },

  // West Ham
  {
    firstName: "Jarrod",
    lastName: "Bowen",
    age: 27,
    nationality: "England",
    position: "RW",
    overallRating: 84,
    potential: 86,
    pace: 85,
    shooting: 84,
    passing: 79,
    dribbling: 85,
    defense: 55,
    physical: 79,
    height: 180,
    weight: 75,
    club: "West Ham United",
    contractEndYear: 2026,
    isYouthPlayer: false,
    preferredFoot: "right",
  },
];

// ============================================
// LA LIGA CLUBS (Spain)
// ============================================

export const LA_LIGA_CLUBS: ClubSeed[] = [
  {
    name: "Real Madrid",
    nickname: "Los Blancos",
    abbreviation: "RMA",
    city: "Madrid",
    country: "Spain",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    stadium: "Santiago Bernabéu",
    stadiumCapacity: 81044,
    founded: 1902,
    domesticTitles: 35,
    europeanTitles: 15,
    league: "La Liga",
    budget: 200000000,
    weeklyWages: 3000000,
    facilities: 5,
  },
  {
    name: "Barcelona",
    nickname: "Blaugrana",
    abbreviation: "FCB",
    city: "Barcelona",
    country: "Spain",
    primaryColor: "#004B87",
    secondaryColor: "#D3232F",
    stadium: "Camp Nou",
    stadiumCapacity: 99354,
    founded: 1899,
    domesticTitles: 27,
    europeanTitles: 5,
    league: "La Liga",
    budget: 180000000,
    weeklyWages: 2800000,
    facilities: 5,
  },
  {
    name: "Atlético Madrid",
    nickname: "Colchoneros",
    abbreviation: "ATM",
    city: "Madrid",
    country: "Spain",
    primaryColor: "#E63C3B",
    secondaryColor: "#FFFFFF",
    stadium: "Metropolitano",
    stadiumCapacity: 68456,
    founded: 1903,
    domesticTitles: 11,
    europeanTitles: 3,
    league: "La Liga",
    budget: 140000000,
    weeklyWages: 2000000,
    facilities: 5,
  },
  {
    name: "Real Sociedad",
    nickname: "Txuri-Urdin",
    abbreviation: "RSO",
    city: "San Sebastián",
    country: "Spain",
    primaryColor: "#0066CC",
    secondaryColor: "#FFFFFF",
    stadium: "Reale Estadio",
    stadiumCapacity: 42105,
    founded: 1909,
    domesticTitles: 2,
    europeanTitles: 0,
    league: "La Liga",
    budget: 110000000,
    weeklyWages: 1700000,
    facilities: 4,
  },
  {
    name: "Valencia CF",
    nickname: "Los Ches",
    abbreviation: "VCF",
    city: "Valencia",
    country: "Spain",
    primaryColor: "#FFF500",
    secondaryColor: "#000000",
    stadium: "Mestalla",
    stadiumCapacity: 55000,
    founded: 1919,
    domesticTitles: 6,
    europeanTitles: 2,
    league: "La Liga",
    budget: 80000000,
    weeklyWages: 1300000,
    facilities: 3,
  },
  {
    name: "Athletic Bilbao",
    nickname: "Los Leones",
    abbreviation: "ATH",
    city: "Bilbao",
    country: "Spain",
    primaryColor: "#ED1C24",
    secondaryColor: "#FFFFFF",
    stadium: "San Mamés",
    stadiumCapacity: 53289,
    founded: 1898,
    domesticTitles: 8,
    europeanTitles: 0,
    league: "La Liga",
    budget: 95000000,
    weeklyWages: 1500000,
    facilities: 4,
  },
  {
    name: "Villarreal CF",
    nickname: "Amarillo",
    abbreviation: "VIL",
    city: "Villarreal",
    country: "Spain",
    primaryColor: "#FDD835",
    secondaryColor: "#1565C0",
    stadium: "Estadio de la Cerámica",
    stadiumCapacity: 23500,
    founded: 1923,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "La Liga",
    budget: 75000000,
    weeklyWages: 1200000,
    facilities: 4,
  },
  {
    name: "Real Betis",
    nickname: "Bético",
    abbreviation: "RBB",
    city: "Seville",
    country: "Spain",
    primaryColor: "#147D3F",
    secondaryColor: "#FFFFFF",
    stadium: "Benito Villamarín",
    stadiumCapacity: 60721,
    founded: 1907,
    domesticTitles: 2,
    europeanTitles: 0,
    league: "La Liga",
    budget: 85000000,
    weeklyWages: 1400000,
    facilities: 4,
  },
  {
    name: "Real Mallorca",
    nickname: "Bermellón",
    abbreviation: "RMA",
    city: "Palma",
    country: "Spain",
    primaryColor: "#E41D2B",
    secondaryColor: "#FFFFFF",
    stadium: "Iberostar Estadio",
    stadiumCapacity: 23798,
    founded: 1916,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "La Liga",
    budget: 60000000,
    weeklyWages: 900000,
    facilities: 3,
  },
  {
    name: "Sevilla FC",
    nickname: "Sevillismo",
    abbreviation: "SFC",
    city: "Seville",
    country: "Spain",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    stadium: "Sánchez Pizjuán",
    stadiumCapacity: 43883,
    founded: 1890,
    domesticTitles: 1,
    europeanTitles: 6,
    league: "La Liga",
    budget: 90000000,
    weeklyWages: 1450000,
    facilities: 4,
  },
  {
    name: "Girona FC",
    nickname: "Blanc i Vermell",
    abbreviation: "GIR",
    city: "Girona",
    country: "Spain",
    primaryColor: "#E41828",
    secondaryColor: "#FFFFFF",
    stadium: "Municipal de Montilivi",
    stadiumCapacity: 13580,
    founded: 1930,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "La Liga",
    budget: 55000000,
    weeklyWages: 800000,
    facilities: 3,
  },
  {
    name: "Getafe CF",
    nickname: "Los Azulones",
    abbreviation: "GET",
    city: "Getafe",
    country: "Spain",
    primaryColor: "#0066CC",
    secondaryColor: "#0000FF",
    stadium: "Coliseum Alfonso Pérez",
    stadiumCapacity: 17625,
    founded: 1947,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "La Liga",
    budget: 50000000,
    weeklyWages: 750000,
    facilities: 2,
  },
  {
    name: "Real Oviedo",
    nickname: "Los Azules",
    abbreviation: "ROS",
    city: "Oviedo",
    country: "Spain",
    primaryColor: "#0066FF",
    secondaryColor: "#FFFFFF",
    stadium: "Carlos Tartiere",
    stadiumCapacity: 30500,
    founded: 1926,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "La Liga",
    budget: 45000000,
    weeklyWages: 700000,
    facilities: 2,
  },
  {
    name: "Rayo Vallecano",
    nickname: "Rayo",
    abbreviation: "RYV",
    city: "Madrid",
    country: "Spain",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    stadium: "Estadio de Vallecas",
    stadiumCapacity: 14708,
    founded: 1924,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "La Liga",
    budget: 48000000,
    weeklyWages: 720000,
    facilities: 2,
  },
  {
    name: "Real Valladolid",
    nickname: "Pucelanos",
    abbreviation: "RVD",
    city: "Valladolid",
    country: "Spain",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000080",
    stadium: "José Zorrilla",
    stadiumCapacity: 26572,
    founded: 1929,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "La Liga",
    budget: 50000000,
    weeklyWages: 750000,
    facilities: 2,
  },
  {
    name: "UD Almería",
    nickname: "Almerienses",
    abbreviation: "UDA",
    city: "Almería",
    country: "Spain",
    primaryColor: "#FF0000",
    secondaryColor: "#FFFFFF",
    stadium: "Estadio de Almería",
    stadiumCapacity: 16711,
    founded: 1989,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "La Liga",
    budget: 40000000,
    weeklyWages: 600000,
    facilities: 2,
  },
  {
    name: "CD Leganés",
    nickname: "Pepineros",
    abbreviation: "LEG",
    city: "Leganés",
    country: "Spain",
    primaryColor: "#001F3F",
    secondaryColor: "#FFFFFF",
    stadium: "Butarque",
    stadiumCapacity: 12454,
    founded: 1986,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "La Liga",
    budget: 42000000,
    weeklyWages: 630000,
    facilities: 2,
  },
  {
    name: "Real Zaragoza",
    nickname: "Aragoneses",
    abbreviation: "RZA",
    city: "Zaragoza",
    country: "Spain",
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF0000",
    stadium: "La Romareda",
    stadiumCapacity: 41000,
    founded: 1932,
    domesticTitles: 2,
    europeanTitles: 0,
    league: "La Liga",
    budget: 55000000,
    weeklyWages: 800000,
    facilities: 3,
  },
  {
    name: "UD Las Palmas",
    nickname: "Amarillos",
    abbreviation: "ULP",
    city: "Las Palmas",
    country: "Spain",
    primaryColor: "#FDD835",
    secondaryColor: "#000000",
    stadium: "Gran Canaria",
    stadiumCapacity: 31556,
    founded: 1949,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "La Liga",
    budget: 45000000,
    weeklyWages: 700000,
    facilities: 2,
  },
  {
    name: "Cádiz CF",
    nickname: "Cadistas",
    abbreviation: "CAD",
    city: "Cádiz",
    country: "Spain",
    primaryColor: "#FFCD39",
    secondaryColor: "#003DA5",
    stadium: "Ramón Blancharte",
    stadiumCapacity: 22000,
    founded: 1910,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "La Liga",
    budget: 40000000,
    weeklyWages: 600000,
    facilities: 2,
  },
];

// ============================================
// LA LIGA PLAYERS (Spain Sample)
// ============================================

export const LA_LIGA_PLAYERS: PlayerSeed[] = [
  // Real Madrid
  {
    firstName: "Vinícius",
    lastName: "Júnior",
    age: 24,
    nationality: "Brazil",
    position: "LW",
    overallRating: 92,
    potential: 95,
    pace: 94,
    shooting: 87,
    passing: 82,
    dribbling: 94,
    defense: 48,
    physical: 82,
    height: 180,
    weight: 73,
    club: "Real Madrid",
    contractEndYear: 2027,
    isYouthPlayer: false,
    preferredFoot: "left",
  },
  {
    firstName: "Karim",
    lastName: "Benzema",
    age: 36,
    nationality: "France",
    position: "ST",
    overallRating: 89,
    potential: 89,
    pace: 82,
    shooting: 94,
    passing: 88,
    dribbling: 88,
    defense: 42,
    physical: 85,
    height: 185,
    weight: 81,
    club: "Real Madrid",
    contractEndYear: 2025,
    isYouthPlayer: false,
    preferredFoot: "right",
  },

  // Barcelona
  {
    firstName: "Robert",
    lastName: "Lewandowski",
    age: 36,
    nationality: "Poland",
    position: "ST",
    overallRating: 91,
    potential: 91,
    pace: 79,
    shooting: 95,
    passing: 85,
    dribbling: 87,
    defense: 39,
    physical: 84,
    height: 187,
    weight: 81,
    club: "Barcelona",
    contractEndYear: 2026,
    isYouthPlayer: false,
    preferredFoot: "right",
  },
  {
    firstName: "Gavi",
    lastName: "Martínez",
    age: 20,
    nationality: "Spain",
    position: "CM",
    overallRating: 83,
    potential: 94,
    pace: 83,
    shooting: 74,
    passing: 85,
    dribbling: 88,
    defense: 70,
    physical: 68,
    height: 173,
    weight: 65,
    club: "Barcelona",
    contractEndYear: 2027,
    isYouthPlayer: false,
    preferredFoot: "right",
  },

  // Atlético Madrid
  {
    firstName: "Antoine",
    lastName: "Griezmann",
    age: 33,
    nationality: "France",
    position: "SCC",
    overallRating: 89,
    potential: 89,
    pace: 84,
    shooting: 88,
    passing: 82,
    dribbling: 87,
    defense: 65,
    physical: 79,
    height: 176,
    weight: 71,
    club: "Atlético Madrid",
    contractEndYear: 2026,
    isYouthPlayer: false,
    preferredFoot: "left",
  },
];

// ============================================
// SERIE A CLUBS (Italy)
// ============================================

export const SERIE_A_CLUBS: ClubSeed[] = [
  {
    name: "Inter Milan",
    nickname: "Nerazzurri",
    abbreviation: "INT",
    city: "Milan",
    country: "Italy",
    primaryColor: "#000000",
    secondaryColor: "#0066FF",
    stadium: "San Siro",
    stadiumCapacity: 80018,
    founded: 1908,
    domesticTitles: 19,
    europeanTitles: 3,
    league: "Serie A",
    budget: 160000000,
    weeklyWages: 2500000,
    facilities: 5,
  },
  {
    name: "AC Milan",
    nickname: "Rossoneri",
    abbreviation: "ACM",
    city: "Milan",
    country: "Italy",
    primaryColor: "#FF0000",
    secondaryColor: "#000000",
    stadium: "San Siro",
    stadiumCapacity: 80018,
    founded: 1899,
    domesticTitles: 19,
    europeanTitles: 7,
    league: "Serie A",
    budget: 140000000,
    weeklyWages: 2200000,
    facilities: 5,
  },
  {
    name: "Juventus",
    nickname: "Bianconeri",
    abbreviation: "JUV",
    city: "Turin",
    country: "Italy",
    primaryColor: "#FFFFFF",
    secondaryColor: "#000000",
    stadium: "Allianz Stadium",
    stadiumCapacity: 41507,
    founded: 1897,
    domesticTitles: 36,
    europeanTitles: 2,
    league: "Serie A",
    budget: 150000000,
    weeklyWages: 2300000,
    facilities: 5,
  },
  {
    name: "SSC Napoli",
    nickname: "Partenopei",
    abbreviation: "NAP",
    city: "Naples",
    country: "Italy",
    primaryColor: "#0A5BA8",
    secondaryColor: "#FFFFFF",
    stadium: "San Paolo",
    stadiumCapacity: 50488,
    founded: 1926,
    domesticTitles: 3,
    europeanTitles: 0,
    league: "Serie A",
    budget: 120000000,
    weeklyWages: 1800000,
    facilities: 4,
  },
  {
    name: "AS Roma",
    nickname: "Giallorossi",
    abbreviation: "ASR",
    city: "Rome",
    country: "Italy",
    primaryColor: "#E8102E",
    secondaryColor: "#F9C62A",
    stadium: "Olimpico",
    stadiumCapacity: 72698,
    founded: 1927,
    domesticTitles: 3,
    europeanTitles: 0,
    league: "Serie A",
    budget: 110000000,
    weeklyWages: 1700000,
    facilities: 4,
  },
  {
    name: "Atalanta BC",
    nickname: "Nerazzurri",
    abbreviation: "ATA",
    city: "Bergamo",
    country: "Italy",
    primaryColor: "#000000",
    secondaryColor: "#0066FF",
    stadium: "Gewiss Stadium",
    stadiumCapacity: 26599,
    founded: 1907,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "Series",
    budget: 90000000,
    weeklyWages: 1400000,
    facilities: 4,
  },
  {
    name: "UC Sampdoria",
    nickname: "Blucerchiati",
    abbreviation: "SMP",
    city: "Genoa",
    country: "Italy",
    primaryColor: "#003DA5",
    secondaryColor: "#FFFFFF",
    stadium: "Luigi Ferraris",
    stadiumCapacity: 36599,
    founded: 1946,
    domesticTitles: 2,
    europeanTitles: 0,
    league: "Serie A",
    budget: 65000000,
    weeklyWages: 1000000,
    facilities: 3,
  },
  {
    name: "Genoa CFC",
    nickname: "Rossoblù",
    abbreviation: "GEN",
    city: "Genoa",
    country: "Italy",
    primaryColor: "#E21E3C",
    secondaryColor: "#0066CC",
    stadium: "Luigi Ferraris",
    stadiumCapacity: 36599,
    founded: 1893,
    domesticTitles: 9,
    europeanTitles: 0,
    league: "Serie A",
    budget: 60000000,
    weeklyWages: 900000,
    facilities: 3,
  },
  {
    name: "Fiorentina",
    nickname: "Violetti",
    abbreviation: "FIO",
    city: "Florence",
    country: "Italy",
    primaryColor: "#862D96",
    secondaryColor: "#FFFFFF",
    stadium: "Artemio Franchi",
    stadiumCapacity: 43622,
    founded: 1926,
    domesticTitles: 2,
    europeanTitles: 0,
    league: "Serie A",
    budget: 85000000,
    weeklyWages: 1300000,
    facilities: 4,
  },
  {
    name: "Hellas Verona",
    nickname: "Gialloblù",
    abbreviation: "HEL",
    city: "Verona",
    country: "Italy",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    stadium: "Stadio Marcantonio Bentegodi",
    stadiumCapacity: 39059,
    founded: 1903,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "Serie A",
    budget: 55000000,
    weeklyWages: 800000,
    facilities: 3,
  },
  {
    name: "Torino FC",
    nickname: "Granata",
    abbreviation: "TOR",
    city: "Turin",
    country: "Italy",
    primaryColor: "#D3112E",
    secondaryColor: "#FFFFFF",
    stadium: "Olimpico Grande Torino",
    stadiumCapacity: 27694,
    founded: 1906,
    domesticTitles: 7,
    europeanTitles: 0,
    league: "Serie A",
    budget: 70000000,
    weeklyWages: 1100000,
    facilities: 3,
  },
  {
    name: "Udinese Calcio",
    nickname: "Friulani",
    abbreviation: "UDI",
    city: "Udine",
    country: "Italy",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    stadium: "Friuli",
    stadiumCapacity: 25144,
    founded: 1896,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "Serie A",
    budget: 50000000,
    weeklyWages: 750000,
    facilities: 3,
  },
  {
    name: "Bologna FC",
    nickname: "Rossoblù",
    abbreviation: "BOL",
    city: "Bologna",
    country: "Italy",
    primaryColor: "#E21E3C",
    secondaryColor: "#003DA5",
    stadium: "Renato Dall'Ara",
    stadiumCapacity: 38279,
    founded: 1909,
    domesticTitles: 7,
    europeanTitles: 0,
    league: "Serie A",
    budget: 60000000,
    weeklyWages: 900000,
    facilities: 3,
  },
  {
    name: "Sassuolo",
    nickname: "Neroverdi",
    abbreviation: "SAS",
    city: "Reggio Emilia",
    country: "Italy",
    primaryColor: "#000000",
    secondaryColor: "#00FF00",
    stadium: "Mapei Stadium",
    stadiumCapacity: 21040,
    founded: 1922,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "Serie A",
    budget: 55000000,
    weeklyWages: 800000,
    facilities: 3,
  },
  {
    name: "AS Empoli",
    nickname: "Azzurri",
    abbreviation: "EMP",
    city: "Empoli",
    country: "Italy",
    primaryColor: "#003DA5",
    secondaryColor: "#FFFFFF",
    stadium: "Stadio Carlo Castellani",
    stadiumCapacity: 16021,
    founded: 1920,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "Serie A",
    budget: 45000000,
    weeklyWages: 700000,
    facilities: 2,
  },
  {
    name: "Lecce",
    nickname: "Giallorossi",
    abbreviation: "LEC",
    city: "Lecce",
    country: "Italy",
    primaryColor: "#FFCC00",
    secondaryColor: "#FF0000",
    stadium: "Via del Mare",
    stadiumCapacity: 27694,
    founded: 1908,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "Serie A",
    budget: 40000000,
    weeklyWages: 600000,
    facilities: 2,
  },
  {
    name: "Lazio",
    nickname: "Biancocelesti",
    abbreviation: "LAZ",
    city: "Rome",
    country: "Italy",
    primaryColor: "#FFFFFF",
    secondaryColor: "#003DA5",
    stadium: "Olimpico",
    stadiumCapacity: 72698,
    founded: 1900,
    domesticTitles: 2,
    europeanTitles: 0,
    league: "Serie A",
    budget: 95000000,
    weeklyWages: 1500000,
    facilities: 4,
  },
  {
    name: "Como 1907",
    nickname: "Lariani",
    abbreviation: "COM",
    city: "Como",
    country: "Italy",
    primaryColor: "#003DA5",
    secondaryColor: "#FFFFFF",
    stadium: "Stadio Giuseppe Sinigaglia",
    stadiumCapacity: 13726,
    founded: 1907,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "Serie A",
    budget: 40000000,
    weeklyWages: 600000,
    facilities: 2,
  },
  {
    name: "Monza",
    nickname: "Biancorossi",
    abbreviation: "MON",
    city: "Monza",
    country: "Italy",
    primaryColor: "#FFFFFF",
    secondaryColor: "#FF0000",
    stadium: "Stadio Brianteo",
    stadiumCapacity: 16303,
    founded: 1912,
    domesticTitles: 0,
    europeanTitles: 0,
    league: "Serie A",
    budget: 45000000,
    weeklyWages: 700000,
    facilities: 2,
  },
  {
    name: "Parma FC",
    nickname: "Crociati",
    abbreviation: "PAR",
    city: "Parma",
    country: "Italy",
    primaryColor: "#FFCC00",
    secondaryColor: "#003DA5",
    stadium: "Stadio Ennio Tardini",
    stadiumCapacity: 25813,
    founded: 1913,
    domesticTitles: 2,
    europeanTitles: 3,
    league: "Serie A",
    budget: 50000000,
    weeklyWages: 750000,
    facilities: 3,
  },
];

// ============================================
// SERIE A PLAYERS (Italy Sample)
// ============================================

export const SERIE_A_PLAYERS: PlayerSeed[] = [
  // Inter Milan
  {
    firstName: "Lautaro",
    lastName: "Martínez",
    age: 27,
    nationality: "Argentina",
    position: "ST",
    overallRating: 90,
    potential: 92,
    pace: 87,
    shooting: 91,
    passing: 81,
    dribbling: 88,
    defense: 45,
    physical: 82,
    height: 181,
    weight: 76,
    club: "Inter Milan",
    contractEndYear: 2027,
    isYouthPlayer: false,
    preferredFoot: "right",
  },
];

// ============================================
// SAMPLE DATA EXPORT - Add more as needed
// ============================================

export const BUNDESLIGA_CLUBS: ClubSeed[] = [];
export const LIGUE_1_CLUBS: ClubSeed[] = [];
export const BUNDESLIGA_PLAYERS: PlayerSeed[] = [];
export const LIGUE_1_PLAYERS: PlayerSeed[] = [];

// Will expand with remaining leagues...
