/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/dev/theme-lab`; params?: Router.UnknownInputParams; } | { pathname: `/oauth/callback`; params?: Router.UnknownInputParams; } | { pathname: `/modes/board-expectations`; params?: Router.UnknownInputParams; } | { pathname: `/modes/career-saves`; params?: Router.UnknownInputParams; } | { pathname: `/modes/create_a_club`; params?: Router.UnknownInputParams; } | { pathname: `/modes/financial`; params?: Router.UnknownInputParams; } | { pathname: `/modes/fixtures`; params?: Router.UnknownInputParams; } | { pathname: `/modes/manager`; params?: Router.UnknownInputParams; } | { pathname: `/modes/match-report`; params?: Router.UnknownInputParams; } | { pathname: `/modes/player`; params?: Router.UnknownInputParams; } | { pathname: `/modes/sporting_director`; params?: Router.UnknownInputParams; } | { pathname: `/modes/squad-management`; params?: Router.UnknownInputParams; } | { pathname: `/modes/standings`; params?: Router.UnknownInputParams; } | { pathname: `/modes/transfers`; params?: Router.UnknownInputParams; } | { pathname: `/modes/club-selection`; params?: Router.UnknownInputParams; } | { pathname: `/modes/match-simulation`; params?: Router.UnknownInputParams; } | { pathname: `/modes/tactics`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/dev/theme-lab`; params?: Router.UnknownOutputParams; } | { pathname: `/oauth/callback`; params?: Router.UnknownOutputParams; } | { pathname: `/modes/board-expectations`; params?: Router.UnknownOutputParams; } | { pathname: `/modes/career-saves`; params?: Router.UnknownOutputParams; } | { pathname: `/modes/create_a_club`; params?: Router.UnknownOutputParams; } | { pathname: `/modes/financial`; params?: Router.UnknownOutputParams; } | { pathname: `/modes/fixtures`; params?: Router.UnknownOutputParams; } | { pathname: `/modes/manager`; params?: Router.UnknownOutputParams; } | { pathname: `/modes/match-report`; params?: Router.UnknownOutputParams; } | { pathname: `/modes/player`; params?: Router.UnknownOutputParams; } | { pathname: `/modes/sporting_director`; params?: Router.UnknownOutputParams; } | { pathname: `/modes/squad-management`; params?: Router.UnknownOutputParams; } | { pathname: `/modes/standings`; params?: Router.UnknownOutputParams; } | { pathname: `/modes/transfers`; params?: Router.UnknownOutputParams; } | { pathname: `/modes/club-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/modes/match-simulation`; params?: Router.UnknownOutputParams; } | { pathname: `/modes/tactics`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/dev/theme-lab${`?${string}` | `#${string}` | ''}` | `/oauth/callback${`?${string}` | `#${string}` | ''}` | `/modes/board-expectations${`?${string}` | `#${string}` | ''}` | `/modes/career-saves${`?${string}` | `#${string}` | ''}` | `/modes/create_a_club${`?${string}` | `#${string}` | ''}` | `/modes/financial${`?${string}` | `#${string}` | ''}` | `/modes/fixtures${`?${string}` | `#${string}` | ''}` | `/modes/manager${`?${string}` | `#${string}` | ''}` | `/modes/match-report${`?${string}` | `#${string}` | ''}` | `/modes/player${`?${string}` | `#${string}` | ''}` | `/modes/sporting_director${`?${string}` | `#${string}` | ''}` | `/modes/squad-management${`?${string}` | `#${string}` | ''}` | `/modes/standings${`?${string}` | `#${string}` | ''}` | `/modes/transfers${`?${string}` | `#${string}` | ''}` | `/modes/club-selection${`?${string}` | `#${string}` | ''}` | `/modes/match-simulation${`?${string}` | `#${string}` | ''}` | `/modes/tactics${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/dev/theme-lab`; params?: Router.UnknownInputParams; } | { pathname: `/oauth/callback`; params?: Router.UnknownInputParams; } | { pathname: `/modes/board-expectations`; params?: Router.UnknownInputParams; } | { pathname: `/modes/career-saves`; params?: Router.UnknownInputParams; } | { pathname: `/modes/create_a_club`; params?: Router.UnknownInputParams; } | { pathname: `/modes/financial`; params?: Router.UnknownInputParams; } | { pathname: `/modes/fixtures`; params?: Router.UnknownInputParams; } | { pathname: `/modes/manager`; params?: Router.UnknownInputParams; } | { pathname: `/modes/match-report`; params?: Router.UnknownInputParams; } | { pathname: `/modes/player`; params?: Router.UnknownInputParams; } | { pathname: `/modes/sporting_director`; params?: Router.UnknownInputParams; } | { pathname: `/modes/squad-management`; params?: Router.UnknownInputParams; } | { pathname: `/modes/standings`; params?: Router.UnknownInputParams; } | { pathname: `/modes/transfers`; params?: Router.UnknownInputParams; } | { pathname: `/modes/club-selection`; params?: Router.UnknownInputParams; } | { pathname: `/modes/match-simulation`; params?: Router.UnknownInputParams; } | { pathname: `/modes/tactics`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
